# Generated by Django 6.0.6 on 2026-07-07 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compensation', models.FloatField()),
                ('career_progression', models.FloatField()),
                ('work_life_balance', models.FloatField()),
                ('manager_relationship', models.FloatField()),
                ('predicted_satisfaction', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hr_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
