# Generated by Django 6.0.6 on 2026-07-07 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='satisfactionprediction',
            options={},
        ),
        migrations.RenameField(
            model_name='satisfactionprediction',
            old_name='predicted_satisfaction',
            new_name='predicted_score',
        ),
        migrations.RemoveField(
            model_name='satisfactionprediction',
            name='hr_manager',
        ),
        migrations.AddField(
            model_name='satisfactionprediction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='satisfactionprediction',
            name='career_progression',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='satisfactionprediction',
            name='compensation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='satisfactionprediction',
            name='manager_relationship',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='satisfactionprediction',
            name='work_life_balance',
            field=models.IntegerField(),
        ),
    ]
